name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.2.1
      with:
        angular_project_dir: ./projects/cube3d-component-showcase
        build_configuration: staging # The build environment for the app. please look configurations in your angular.json
        base_href: https://atap23.github.io/cube3d-component/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        build_folder: projects/cube3d-component-showcase # The folder where your project is supposed to be after running ng build by the action.
